name: Docker Image Check

on:
  pull_request:
    branches:
      - master

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t emulator-image:${{ github.sha }} .

      - name: Check if the Docker image runs
        run: |
          docker run -d -e APPIUM=true --name emulator-container emulator-image:${{ github.sha }}

          echo "Waiting for the container to start..."
          sleep 10  

          if [[ $(docker ps -q -f name=emulator-container) ]]; then
              echo "Container is up and running."
          else
              echo "Container failed to start."
              exit 1
          fi

          docker logs emulator-container

      - name: Clean up
        run: |
          docker stop emulator-container
          docker rm emulator-container